# Windows Server Core with Visual Studio Build Tools
FROM mcr.microsoft.com/windows/servercore:ltsc2022

# Install VS Build Tools with required components
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_buildtools.exe" -OutFile "vs_buildtools.exe" ; \
    Start-Process -FilePath ".\vs_buildtools.exe" -ArgumentList "--quiet", "--wait", \
      "--add", "Microsoft.VisualStudio.Workload.VCTools", \
      "--add", "Microsoft.VisualStudio.Component.Windows10SDK.19041", \
      "--add", "Microsoft.VisualStudio.Component.VC.CMake.Project" \
      -NoNewWindow -Wait ; \
    Remove-Item ".\vs_buildtools.exe"

# Set environment for builds
RUN setx PATH "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin;%PATH%" /M

WORKDIR C:\workspace
